# Render Blueprint for EcoRideConnect
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: ecoride-connect
    env: node
    plan: free
    autoDeploy: true
    rootDir: EcoRideConnect
    buildCommand: |
      npm ci --include=dev
      # Ensure client builds with correct base path on Render (serves from '/')
      VITE_BASE_PATH=/ npm run build
  # Only run migrations if a DATABASE_URL is provided; otherwise start in SIMPLE_AUTH memory mode
  startCommand: bash -lc 'if [ -n "$DATABASE_URL" ]; then npm run db:push; fi; npm run start'
    # Health check hits the API health endpoint (server answers when ready)
    healthCheckPath: /api/health
    # Environment
    envVars:
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: trusty-diorama-475905-c3
      - key: GOOGLE_CLOUD_PROJECT
        value: trusty-diorama-475905-c3
      - key: SESSION_SECRET
        generateValue: true
      - key: VITE_BASE_PATH
        value: /
      # Run in memory mode on Render unless a DATABASE_URL is provided
      # This prevents crashes when Neon isn't configured yet
      - key: SIMPLE_AUTH
        value: 'true'
      # Auth/dev toggles
      - key: VITE_SIMPLE_AUTH
        value: 'true'
      - key: ALLOW_SIMPLE_AUTH_ROUTES
        value: 'true'
      - key: COOKIE_SECURE
        value: 'true'
  # Note: Set DATABASE_URL and optional API keys in the Render Dashboard after creation.
