name: CI - build & optional deploy

on:
  push:
    branches: [ main, chore/** ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      NODE_OPTIONS: --max-old-space-size=4096
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (client + server)
        working-directory: ./
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ecoride-build
          path: |
            EcoRideConnect/dist

  deploy-render:
    needs: build
    runs-on: ubuntu-latest
    env:
      RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
    steps:
      - name: Trigger Render deploy (if secrets present)
        if: ${{ env.RENDER_SERVICE_ID != '' && env.RENDER_API_KEY != '' }}
        run: |
          echo "Triggering Render deploy for service $RENDER_SERVICE_ID"
          curl -s -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          | jq -r '.message, .id'

  deploy-vercel:
    needs: build
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel

      - name: Deploy frontend to Vercel (if configured)
        if: ${{ env.VERCEL_TOKEN != '' && env.VERCEL_PROJECT_ID != '' }}
        working-directory: EcoRideConnect/client
        run: |
          # Use Vercel CLI to redeploy the client. This requires the Vercel project to be pre-configured.
          npx vercel --prod --token "$VERCEL_TOKEN" --confirm --project "$VERCEL_PROJECT_ID"
